In [18]:
import pandas as pd
import json
pd.set_option('display.max_columns', None)

In [14]:
filepath = '../../data/network/networkrepo-linkedin/soc-linkedin.nodes'
df = pd.read_csv(filepath, header =None)
df.head()

                                      0
0  0\tpub-sandra-arana-querol-2b-561-73
1                    1\tin-sehrishhafiz
2          2\tpub-heba-bayoumi-16-a6-97
3       3\tpub-aysha-binbraik-5-90b-b49
4                     4\tin-rubabadowla

In [15]:
# df = df[0].str.split('\t')
df[['A', 'B']] = df[0].str.split('\t', n=1, expand=True)
df.head()

                                      0  A                                  B
0  0\tpub-sandra-arana-querol-2b-561-73  0  pub-sandra-arana-querol-2b-561-73
1                    1\tin-sehrishhafiz  1                    in-sehrishhafiz
2          2\tpub-heba-bayoumi-16-a6-97  2          pub-heba-bayoumi-16-a6-97
3       3\tpub-aysha-binbraik-5-90b-b49  3       pub-aysha-binbraik-5-90b-b49
4                     4\tin-rubabadowla  4                     in-rubabadowla

In [19]:
# 2nd dataset
ppl_df = pd.read_csv('../../data/people/us_profiles/10000_random_us_people_profiles.csv')

ppl_df.head()

,Unnamed: 0,public_identifier,profile_pic_url,background_cover_image_url,first_name,last_name,full_name,occupation,headline,summary,country,country_full_name,city,state,experiences,education,languages,accomplishment_organisations,accomplishment_publications,accomplishment_honors_awards,accomplishment_patents,accomplishment_courses,accomplishment_projects,accomplishment_test_scores,volunteer_work,certifications,connections,people_also_viewed,recommendations,activities,similarly_named_profiles,articles,groups,skills,inferred_salary,github,facebook,gender,birth_date,industry,interests
0,0,none,https://static-exp1.licdn.com/sc/h/244xhbkr7g4...,https://static-exp1.licdn.com/sc/h/5q92mjc5c51...,Jeff,B.,Jeff B.,"AVP, Life Underwriting at Illinois Mutual",Illinois Mutual,NaN,US,United States of America,Normal,Illinois,"[{'starts_at': {'day': 1, 'month': 8, 'year': ...","[{'starts_at': None, 'ends_at': None, 'field_o...",[],[],[],[],[],[],[],[],[],"[{'starts_at': None, 'ends_at': None, 'url': N...",380.0,[{'link': 'https://www.linkedin.com/in/katie-m...,[],[],"[{'name': 'Jeff B', 'link': 'https://www.linke...",[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,a-a-,https://media-exp1.licdn.com/dms/image/C4E03AQ...,https://static-exp1.licdn.com/sc/h/5q92mjc5c51...,Abdulaziz,Alyahya,Abdulaziz Alyahya,NaN,Student at Rowan University,Iâ€™m an enthusiastic business management and Hu...,US,United States of America,Glassboro,New Jersey,[],"[{'starts_at': {'day': 1, 'month': 1, 'year': ...",[],[],[],[],[],[],[],[],[],[],40.0,[{'link': 'https://sa.linkedin.com/in/mbashara...,[],"[{'title': 'Welcome to the team, Corrine! Fun ...","[{'name': 'abdulaziz alyahya', 'link': 'https:...",[],[{'profile_pic_url': 'https://media-exp1.licdn...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,a-a-bailey,https://media-exp1.licdn.com/dms/image/C4E03AQ...,https://static-exp1.licdn.com/sc/h/5q92mjc5c51...,Andrew,Bailey,Andrew Bailey,Science & Technology Counsel at National Pork ...,National Pork Producers Council,Experienced government affairs and public poli...,US,United States of America,Washington,District of Columbia,"[{'starts_at': {'day': 1, 'month': 4, 'year': ...","[{'starts_at': {'day': 1, 'month': 1, 'year': ...",[],[],[],[],[],[],[],[],[],[],400.0,[{'link': 'https://www.linkedin.com/in/jack-fr...,[],[],"[{'name': 'Andrew Bailey', 'link': 'https://ca...",[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,a-a-cabrera,https://media-exp1.licdn.com/dms/image/C4E03AQ...,https://static-exp1.licdn.com/sc/h/5q92mjc5c51...,Alex,Cabrera,Alex Cabrera,Research Intern at Apple,PhD Student at Carnegie Mellon University,NaN,US,United States of America,Fairfax County,Virginia,"[{'starts_at': {'day': 1, 'month': 5, 'year': ...","[{'starts_at': {'day': 1, 'month': 1, 'year': ...","['English', 'Spanish', 'French']",[],[],"[{'title': 'Stamps Leadership Scholarship', 'i...",[],[],"[{'starts_at': {'day': 1, 'month': 4, 'year': ...",[],[],[],500.0,[{'link': 'https://www.linkedin.com/in/willepp...,['K Kulkarni\n \n \n\n\n\n ...,[{'title': 'Delighted to announce Iâ€™ll be inte...,"[{'name': 'Alex Cabrera', 'link': 'https://www...",[],[{'profile_pic_url': 'https://media-exp1.licdn...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,a-a-de-oliveira-manuel,https://media-exp1.licdn.com/dms/image/C4E03AQ...,https://media-exp1.licdn.com/dms/image/C4D16AQ...,Alcino de Oliveira,Manuel,Alcino de Oliveira Manuel,Marketing Consultant at Alcino Media LLC,Founder @ AlcinoMedia | Facebook/Meta & Google...,"I use the drive and commitment to help, inspir...",US,United States of America,Miami,Florida,"[{'starts_at': {'day': 1, 'month': 8, 'year': ...",[],[],[],[],[],[],[],[],[],[],[],30.0,[{'link': 'https://www.linkedin.com/in/keith-w...,[],"[{'title': 'Love it ðŸ’ª', 'link': 'https://www.l...",[],[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
ppl_df.tail()

,Unnamed: 0,public_identifier,profile_pic_url,background_cover_image_url,first_name,last_name,full_name,occupation,headline,summary,country,country_full_name,city,state,experiences,education,languages,accomplishment_organisations,accomplishment_publications,accomplishment_honors_awards,accomplishment_patents,accomplishment_courses,accomplishment_projects,accomplishment_test_scores,volunteer_work,certifications,connections,people_also_viewed,recommendations,activities,similarly_named_profiles,articles,groups,skills,inferred_salary,github,facebook,gender,birth_date,industry,interests
9995,9995,aaron-dominowski,https://static-exp1.licdn.com/sc/h/244xhbkr7g4...,https://static-exp1.licdn.com/sc/h/5q92mjc5c51...,Aaron,Dominowski,Aaron Dominowski,NaN,Student at Delta College\nInformation Technology,NaN,US,United States of America,Greater Saginaw-Midland-Bay City Area,NaN,[],"[{'starts_at': {'day': 1, 'month': 1, 'year': ...",[],[],[],[],[],[],[],[],[],[],NaN,[{'link': 'https://www.linkedin.com/in/helen-g...,[],[],"[{'name': 'Aaron Dominowski', 'link': 'https:/...",[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9996,9996,aaron-dominy,https://media-exp1.licdn.com/dms/image/C4E03AQ...,https://static-exp1.licdn.com/sc/h/5q92mjc5c51...,"Aaron Dominy,",MBA,"Aaron Dominy, MBA","Engagement Manager at Onica, a Rackspace Techn...",Engagement Manager at Rackspace Technology,Experienced Agile/Scrum management consultant ...,US,United States of America,Houston,Texas,"[{'starts_at': {'day': 1, 'month': 11, 'year':...","[{'starts_at': {'day': 1, 'month': 1, 'year': ...",[],[],[],[{'title': 'The National Society of Leadership...,[],[],[],[],"[{'starts_at': {'day': 1, 'month': 3, 'year': ...","[{'starts_at': {'day': 1, 'month': 5, 'year': ...",500.0,[{'link': 'https://www.linkedin.com/in/sharonc...,[],[],[],[],[{'profile_pic_url': 'https://media-exp1.licdn...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9997,9997,aaron-don-williams,https://static-exp1.licdn.com/sc/h/244xhbkr7g4...,https://static-exp1.licdn.com/sc/h/5q92mjc5c51...,Aaron,Williams,Aaron Williams,Community Manager/ Developer Advocate -Astra S...,Community Manager/ Developer Advocate -Astra S...,Aaron is passionate about bringing new technol...,US,United States of America,San Ramon,California,"[{'starts_at': {'day': 1, 'month': 6, 'year': ...","[{'starts_at': None, 'ends_at': None, 'field_o...",[],[],[],"[{'title': 'SAP Catalyst', 'issuer': 'SAP', 'i...",[{'title': 'Vehicular-based earthquake early w...,[],[],[],[],"[{'starts_at': {'day': 1, 'month': 9, 'year': ...",500.0,[{'link': 'https://it.linkedin.com/in/michele-...,"['Bonnie Barker, PMP\n \n \n\n\n...",[],"[{'name': 'Aaron Williams', 'link': 'https://w...",[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9998,9998,aaron-dona,https://media-exp1.licdn.com/dms/image/C5103AQ...,https://media-exp1.licdn.com/dms/image/C5616AQ...,Aaron,Dona,Aaron Dona,Senior Technical Agent at 343 Industries,Tech Support Agent at 343 Industries,I enjoy cutting loose with artistic expression...,US,United States of America,Greater Seattle Area,NaN,"[{'starts_at': {'day': 1, 'month': 1, 'year': ...","[{'starts_at': {'day': 1, 'month': 1, 'year': ...",[],[],[],[],[],"[{'name': '(Raster Images) Photoshop', 'number...","[{'starts_at': {'day': 1, 'month': 1, 'year': ...",[],"[{'starts_at': None, 'ends_at': None, 'cause':...",[],153.0,[{'link': 'https://www.linkedin.com/in/anjurul...,['Sue Kellogg\n \n \n\n\n\n ...,[],"[{'name': 'Aaron Dona', 'link': 'https://www.l...",[],[{'profile_pic_url': 'https://media-exp1.licdn...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999,9999,aaron-donald,https://media-exp1.licdn.com/dms/image/C4E03AQ...,https://static-exp1.licdn.com/sc/h/5q92mjc5c51...,Aaron,Donald,Aaron Donald,Production Foreman at Seneca Foods Corporation,"Sales, Marketing, & Management.",NaN,US,United States of America,Shelby,Michigan,"[{'starts_at': {'day': 1, 'month': 4, 'year': ...","[{'starts_at': None, 'ends_at': None, 'field_o...",[],[],[],[],[],[],[],[],[],[],44.0,[{'link': 'https://www.linkedin.com/in/sheriek...,[],[{'title': 'A bad road commission saying I hat...,"[{'name': 'Aaron Donald', 'link': 'https://www...",[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df.merge(ppl_df, left_on='B',right_on='public_identifier')

Empty DataFrame
Columns: [0, A, B, Unnamed: 0, public_identifier, profile_pic_url, background_cover_image_url, first_name, last_name, full_name, occupation, headline, summary, country, country_full_name, city, state, experiences, education, languages, accomplishment_organisations, accomplishment_publications, accomplishment_honors_awards, accomplishment_patents, accomplishment_courses, accomplishment_projects, accomplishment_test_scores, volunteer_work, certifications, connections, people_also_viewed, recommendations, activities, similarly_named_profiles, articles, groups, skills, inferred_salary, github, facebook, gender, birth_date, industry, interests]
Index: []

[0 rows x 44 columns]

In [27]:
df[df['B'].str.contains('don-williams')] # aaron-

,0,A,B
228850,228850\tpub-brandon-williamson-6-2a0-547,228850,pub-brandon-williamson-6-2a0-547
455874,455874\tpub-don-williams-0-946-3b1,455874,pub-don-williams-0-946-3b1
455875,455875\tpub-don-williams-0-917-8a5,455875,pub-don-williams-0-917-8a5
684351,684351\tpub-haydon-williams-20-314-7a8,684351,pub-haydon-williams-20-314-7a8
743301,743301\tpub-brandon-williams-2b-860-467,743301,pub-brandon-williams-2b-860-467
743302,743302\tpub-brandon-williams-20-795-638,743302,pub-brandon-williams-20-795-638
743303,743303\tpub-brandon-williams-14-a95-188,743303,pub-brandon-williams-14-a95-188
1134515,1134515\tpub-don-williamson-8-b80-aa8,1134515,pub-don-williamson-8-b80-aa8
1134516,1134516\tpub-don-williams-12-a5a-873,1134516,pub-don-williams-12-a5a-873
1545403,1545403\tpub-gordon-williamson-25-469-413,1545403,pub-gordon-williamson-25-469-413
1545404,1545404\tpub-gordon-williams-14-533-a8a,1545404,pub-gordon-williams-14-533-a8a
1885121,1885121\tpub-landon-williams-3-255-591,1885121,pub-landon-williams-3-255-591
1976786,1976786\tpub-don-williams-17-233-b3a,1976786,pub-don-williams-17-233-b3a
2015870,2015870\tpub-brandon-williams-6-477-b75,2015870,pub-brandon-williams-6-477-b75
2015871,2015871\tpub-brandon-williams-3b-185-6b1,2015871,pub-brandon-williams-3b-185-6b1
2344671,2344671\tpub-don-williamson-3b-959-7a4,2344671,pub-don-williamson-3b-959-7a4
2344672,2344672\tpub-don-williams-14-a48-a7a,2344672,pub-don-williams-14-a48-a7a
2707287,2707287\tpub-don-williams-0-538-868,2707287,pub-don-williams-0-538-868
2885231,2885231\tpub-sheldon-williamson-5a-219-428,2885231,pub-sheldon-williamson-5a-219-428
3100251,3100251\tpub-don-williamson-28-118-223,3100251,pub-don-williamson-28-118-223
3100252,3100252\tpub-don-williams-2-193-529,3100252,pub-don-williams-2-193-529
3593854,3593854\tpub-don-williams-17-b28-94b,3593854,pub-don-williams-17-b28-94b
3599025,3599025\tpub-des-gordon-williams-14-113-2b6,3599025,pub-des-gordon-williams-14-113-2b6
3649414,3649414\tpub-brandon-williams-49-b54-4a2,3649414,pub-brandon-williams-49-b54-4a2
4370625,4370625\tpub-don-williams-56-ab1-a4,4370625,pub-don-williams-56-ab1-a4
4370626,4370626\tpub-don-williams-2-249-239,4370626,pub-don-williams-2-249-239
4464312,4464312\tpub-brandon-williams-b-b96-a40,4464312,pub-brandon-williams-b-b96-a40
4464313,4464313\tpub-brandon-williams-3-508-bab,4464313,pub-brandon-williams-3-508-bab
5433627,5433627\tpub-lyndon-williams-3a-a00-143,5433627,pub-lyndon-williams-3a-a00-143
5433628,5433628\tpub-lyndon-williams-16-45a-a97,5433628,pub-lyndon-williams-16-45a-a97
5506220,5506220\tpub-landon-williams-25-809-18a,5506220,pub-landon-williams-25-809-18a
5554014,5554014\tpub-katy-congdon-williams-2-435-617,5554014,pub-katy-congdon-williams-2-435-617
5825607,5825607\tpub-gordon-williamson-4b-598-154,5825607,pub-gordon-williamson-4b-598-154
5825608,5825608\tpub-gordon-williams-16-971-591,5825608,pub-gordon-williams-16-971-591
5984972,5984972\tpub-don-williams-aicp-12-b85-37b,5984972,pub-don-williams-aicp-12-b85-37b
5984973,5984973\tpub-don-williams-5-42a-3b9,5984973,pub-don-williams-5-42a-3b9
5984974,5984974\tpub-don-williams-4a-916-26a,5984974,pub-don-williams-4a-916-26a
5984975,5984975\tpub-don-williams-36-167-9a,5984975,pub-don-williams-36-167-9a
5984976,5984976\tpub-don-williams-3-562-869,5984976,pub-don-williams-3-562-869
5984977,5984977\tpub-don-williams-17-4b4-b70,5984977,pub-don-williams-17-4b4-b70
5984978,5984978\tpub-don-williams-0-148-145,5984978,pub-don-williams-0-148-145
6190677,6190677\tpub-brendon-williamson-2b-770-67,6190677,pub-brendon-williamson-2b-770-67
6192890,6192890\tpub-brandon-williams-5a-a43-839,6192890,pub-brandon-williams-5a-a43-839
6192891,6192891\tpub-brandon-williams-2b-819-142,6192891,pub-brandon-williams-2b-819-142
6192892,6192892\tpub-brandon-williams-29-571-631,6192892,pub-brandon-williams-29-571-631
6192893,6192893\tpub-brandon-williams-2-2b5-504,6192893,pub-brandon-williams-2-2b5-504
6192894,6192894\tpub-brandon-williams-16-56a-b27,6192894,pub-brandon-williams-16-56a-b27
6192895,6192895\tpub-brandon-williams-11-211-953,6192895,pub-brandon-williams-11-211-953
6192896,6192896\tpub-brandon-williams-10-367-577,6192896,pub-brandon-williams-10-367-577