In [17]:
import pandas as pd
import os
import json

In [18]:
us_profiles = '../../data/people/us_profiles/10000_random_us_people_profiles.txt'

profile_lst = []
with open(us_profiles, 'r') as f:
    profile_lst = f.readlines()

In [19]:
for i,p in enumerate(profile_lst):
    profile_lst[i] = json.loads(profile_lst[i])
profile_lst[:2]

[{'public_identifier': 'none',
  'profile_pic_url': 'https://static-exp1.licdn.com/sc/h/244xhbkr7g40x6bsu4gi6q4ry',
  'background_cover_image_url': 'https://static-exp1.licdn.com/sc/h/5q92mjc5c51bjlwaj3rs9aa82',
  'first_name': 'Jeff',
  'last_name': 'B.',
  'full_name': 'Jeff B.',
  'occupation': 'AVP, Life Underwriting at Illinois Mutual',
  'headline': 'Illinois Mutual',
  'summary': None,
  'country': 'US',
  'country_full_name': 'United States of America',
  'city': 'Normal',
  'state': 'Illinois',
  'experiences': [{'starts_at': {'day': 1, 'month': 8, 'year': 2018},
    'ends_at': None,
    'company': 'Illinois Mutual',
    'company_linkedin_profile_url': 'https://www.linkedin.com/company/illinois-mutual',
    'title': 'AVP, Life Underwriting',
    'description': None,
    'location': 'Peoria, Illinois Area',
    'logo_url': 'https://media-exp1.licdn.com/dms/image/C4E0BAQEbxRTeOThzQg/company-logo_100_100/0/1523283330240?e=1655942400&v=beta&t=LY8dpbCLm80UJviuyTy6qyEvTNX6WetT-VGkEWijjXc'},
   {'starts_at': {'day': 1, 'month': 1, 'year': 2017},
    'ends_at': {'day': 31, 'month': 8, 'year': 2018},
    'company': 'Illinois Mutual',
    'company_linkedin_profile_url': 'https://www.linkedin.com/company/illinois-mutual',
    'title': 'AVP, Underwriting Operations',
    'description': None,
    'location': None,
    'logo_url': 'https://media-exp1.licdn.com/dms/image/C4E0BAQEbxRTeOThzQg/company-logo_100_100/0/1523283330240?e=1655942400&v=beta&t=LY8dpbCLm80UJviuyTy6qyEvTNX6WetT-VGkEWijjXc'},
   {'starts_at': {'day': 1, 'month': 9, 'year': 2014},
    'ends_at': {'day': 31, 'month': 1, 'year': 2017},
    'company': 'Illinois Mutual',
    'company_linkedin_profile_url': 'https://www.linkedin.com/company/illinois-mutual',
    'title': 'Manager, Underwriting Administration',
    'description': None,
    'location': 'Peoria, Illinois Area',
    'logo_url': 'https://media-exp1.licdn.com/dms/image/C4E0BAQEbxRTeOThzQg/company-logo_100_100/0/1523283330240?e=1655942400&v=beta&t=LY8dpbCLm80UJviuyTy6qyEvTNX6WetT-VGkEWijjXc'},
   {'starts_at': {'day': 1, 'month': 1, 'year': 2013},
    'ends_at': {'day': 30, 'month': 9, 'year': 2014},
    'company': 'TEKsystems',
    'company_linkedin_profile_url': 'https://www.linkedin.com/company/teksystems',
    'title': 'Business Analyst',
    'description': None,
    'location': None,
    'logo_url': 'https://media-exp1.licdn.com/dms/image/C560BAQHvWB-HshcNtA/company-logo_100_100/0/1625161122996?e=1655942400&v=beta&t=9nL6_vVJkFaUOay-2C249Ov4kQyIoqzIe6In7wE8KHM'},
   {'starts_at': {'day': 1, 'month': 1, 'year': 1998},
    'ends_at': {'day': 31, 'month': 12, 'year': 2012},
    'company': 'COUNTRY FinancialÂ®',
    'company_linkedin_profile_url': 'https://www.linkedin.com/company/country-financial-',
    'title': 'Supervisor',
    'description': None,
    'location': None,
    'logo_url': 'https://media-exp1.licdn.com/dms/image/C560BAQGT-DZrm0HW4w/company-logo_100_100/0/1587146899144?e=1655942400&v=beta&t=lrgQvdeYurbfUTbzkxyakHQc_aCYvOqeE2M8NzYdipg'}],
  'education': [{'starts_at': None,
    'ends_at': None,
    'field_of_study': 'Criminal  Justice',
    'degree_name': 'BS',
    'school': 'Illinois State University',
    'school_linkedin_profile_url': 'https://www.linkedin.com/school/illinois-state-university/',
    'description': None,
    'logo_url': 'https://media-exp1.licdn.com/dms/image/C4E0BAQFPU2MERZQbWg/company-logo_100_100/0/1645802911896?e=1655942400&v=beta&t=0tXgxH5ASaX5oYZF3V3Kgt_XeqoWEPBo9PPkWD1eMUg'}],
  'languages': [],
  'accomplishment_organisations': [],
  'accomplishment_publications': [],
  'accomplishment_honors_awards': [],
  'accomplishment_patents': [],
  'accomplishment_courses': [],
  'accomplishment_projects': [],
  'accomplishment_test_scores': [],
  'volunteer_work': [],
  'certifications': [{'starts_at': None,
    'ends_at': None,
    'url': None,
    'name': 'AIRC',
    'license_number': None,
    'display_source': None,
    'authority': 'LOMA'},
   {'starts_at': None,
    'ends_at': None,
    'url': None,
    'name': 'ALMI, ACS',
    'license_number': None,
    'display_source': None,
    'authority': 'LOMA'}],
  'connections': 380,
  'people_also_viewed': [{'link': 'https://www.linkedin.com/in/katie-mccord-jenkins',
    'name': 'Katie McCord Jenkins',
    'summary': 'President at Illinois Mutual',
    'location': 'Peoria Metropolitan Area'},
   {'link': 'https://www.linkedin.com/in/michael-smith-3733192b',
    'name': 'Michael Smith',
    'summary': 'AVP -Worksite & Life Sales at Illinois Mutual',
    'location': 'Greater Chicago Area'},
   {'link': 'https://in.linkedin.com/in/dr-vyoma-mehta-18667019a',
    'name': 'Dr.Vyoma Mehta',
    'summary': 'Aspiring DERMATOLOGIST',
    'location': 'Ahmedabad'},
   {'link': 'https://in.linkedin.com/in/chahat-maru-a73892179',
    'name': 'Chahat Maru',
    'summary': 'Doctor of Philosophy - PhD student  Indian Institute of Management, Ranchi',
    'location': 'Ranchi'},
   {'link': 'https://www.linkedin.com/in/jessica-lindenmeier-93609b12b',
    'name': 'Jessica Lindenmeier',
    'summary': 'Customer Service Representative at M&T Bank',
    'location': 'Georgetown, DE'},
   {'link': 'https://www.linkedin.com/in/jessica-lindenmeier-a95959113',
    'name': 'Jessica Lindenmeier',
    'summary': '--',
    'location': 'United States'},
   {'link': 'https://www.linkedin.com/in/janet-taylor-751abb80',
    'name': 'Janet Taylor',
    'summary': 'Senior Coordinator of Patient Relations and Collections at OSF HealthCare',
    'location': 'United States'},
   {'link': 'https://www.linkedin.com/in/ching-graham-a100b281',
    'name': 'Ching Graham',
    'summary': '--',
    'location': 'United States'},
   {'link': 'https://www.linkedin.com/in/joan-stickelmaier-18164a1b3',
    'name': 'Joan Stickelmaier',
    'summary': '--',
    'location': 'Peoria, IL'},
   {'link': 'https://www.linkedin.com/in/janet-herrold-270ab718',
    'name': 'Janet herrold',
    'summary': 'Investigator at Principal Financial Group',
    'location': 'Des Moines, IA'},
   {'link': 'https://www.linkedin.com/in/rashanda-harris-aa427250',
    'name': 'Rashanda Harris',
    'summary': 'Cost Containment Manager at Amerigroup Corporation',
    'location': 'Virginia Beach, VA'},
   {'link': 'https://www.linkedin.com/in/cindy-walls-5b271913',
    'name': 'Cindy Walls',
    'summary': 'Life Sales Specialist at Illinois Mutual Life Insurance Company',
    'location': 'Indianapolis, IN'},
   {'link': 'https://www.linkedin.com/in/djande01',
    'name': 'Deena Anderson',
    'summary': 'Manager, Worksite Operations at Illinois Mutual',
    'location': 'Greater St. Louis'},
   {'link': 'https://www.linkedin.com/in/jason-clark-92a30816',
    'name': 'Jason Clark',
    'summary': 'Business Analyst at State Farm Insurance',
    'location': 'Normal, IL'},
   {'link': 'https://www.linkedin.com/in/mike-lantz-2744978',
    'name': 'Mike Lantz',
    'summary': 'IT Consultant / Project Manager at EDS',
    'location': 'Farmington, MI'},
   {'link': 'https://www.linkedin.com/in/kris-singh-61684b27',
    'name': 'Kris Singh',
    'summary': 'Project Manager at Hewlett-Packard',
    'location': 'Farmington, MI'},
   {'link': 'https://www.linkedin.com/in/luke-butler-928615110',
    'name': 'Luke Butler',
    'summary': 'Business Analyst at State Farm',
    'location': 'Normal, IL'}],
  'recommendations': [],
  'activities': [],
  'similarly_named_profiles': [{'name': 'Jeff B',
    'link': 'https://www.linkedin.com/in/jeff-b-614a622b',
    'summary': 'Owner at Custom Made Carpets LLC',
    'location': 'Orange City, FL'},
   {'name': 'Jeff B',
    'link': 'https://www.linkedin.com/in/realjeffb',
    'summary': 'Strategy | Strategic Communications | Public Policy | National Security',
    'location': 'United States'},
   {'name': 'Jeff B',
    'link': 'https://ph.linkedin.com/in/jeffb3',
    'summary': 'Seasoned construction/engineering contracts specialist with proven claims and arbitration experience.',
    'location': 'Philippines'},
   {'name': 'Jeff B',
    'link': 'https://www.linkedin.com/in/jeff-b-77626059',
    'summary': 'Owner - Voice Over Artist at Pacific Voiceover',
    'location': 'Springfield, OR'},
   {'name': 'Jeff B.',
    'link': 'https://ca.linkedin.com/in/jeff-b-27267444',
    'summary': 'OPERATIONS: HEAD FOREMAN at GCT',
    'location': 'Vancouver, BC'}],
  'articles': [],
  'groups': [],
  'skills': None,
  'inferred_salary': None,
  'github': None,
  'facebook': None,
  'gender': None,
  'birth_date': None,
  'industry': None,
  'interests': None},
 {'public_identifier': 'a-a-',
  'profile_pic_url': 'https://media-exp1.licdn.com/dms/image/C4E03AQHaXG6hDwWoxw/profile-displayphoto-shrink_200_200/0/1572304136322?e=1652918400&v=beta&t=nAakxVAWgtEv79SkBWDgOT0Iqg7b5xukXaYTibVxjq4',
  'background_cover_image_url': 'https://static-exp1.licdn.com/sc/h/5q92mjc5c51bjlwaj3rs9aa82',
  'first_name': 'Abdulaziz',
  'last_name': 'Alyahya',
  'full_name': 'Abdulaziz Alyahya',
  'occupation': None,
  'headline': 'Student at Rowan University',
  'summary': 'Iâm an enthusiastic business management and Human Resource graduates from Rowan University NJ, USA.',
  'country': 'US',
  'country_full_name': 'United States of America',
  'city': 'Glassboro',
  'state': 'New Jersey',
  'experiences': [],
  'education': [{'starts_at': {'day': 1, 'month': 1, 'year': 2015},
    'ends_at': {'day': 31, 'month': 12, 'year': 2019},
    'field_of_study': None,
    'degree_name': None,
    'school': 'Rowan University',
    'school_linkedin_profile_url': 'https://www.linkedin.com/school/rowan-university/',
    'description': None,
    'logo_url': 'https://media-exp1.licdn.com/dms/image/C4D0BAQF7fuUhXKdviA/company-logo_100_100/0/1566573646760?e=1655942400&v=beta&t=qK549UgmyDvd9KCecEPEVC2mMtwumKOqO-98luAqtQQ'}],
  'languages': [],
  'accomplishment_organisations': [],
  'accomplishment_publications': [],
  'accomplishment_honors_awards': [],
  'accomplishment_patents': [],
  'accomplishment_courses': [],
  'accomplishment_projects': [],
  'accomplishment_test_scores': [],
  'volunteer_work': [],
  'certifications': [],
  'connections': 40,
  'people_also_viewed': [{'link': 'https://sa.linkedin.com/in/mbasharath',
    'name': 'Basharatullah Mohammed',
    'summary': 'ITSM Consultant, ITIL Expert/Managing Professional, PMP',
    'location': 'Riyadh, Saudi Arabia'},
   {'link': 'https://sa.linkedin.com/in/faisal-alfadley-7ab26530',
    'name': 'Faisal AlFadley',
    'summary': 'Treasury Group Director at SPIMACO',
    'location': 'Riyadh, Saudi Arabia'},
   {'link': 'https://sa.linkedin.com/in/rakanalyahya',
    'name': 'ÙÙRakan Mohammed Alyahya',
    'summary': 'Riyadh',
    'location': 'Riyadh, Saudi Arabia'},
   {'link': 'https://sa.linkedin.com/in/mansour-alyahya-assoc-cipd',
    'name': 'Mansour AlYahya Assoc CIPD',
    'summary': 'HR Manager at Acuative Middle East',
    'location': 'Riyadh'},
   {'link': 'https://sa.linkedin.com/in/abdullah-alsubaihi-ba414b128',
    'name': 'Abdullah AlSubaihi',
    'summary': 'Lead Specialist, Operational Excellence at TAWAL- Telecommunications Towers Company',
    'location': 'Saudi Arabia'},
   {'link': 'https://sa.linkedin.com/in/meshael-alromaih-shrm-cp',
    'name': 'Meshael Alromaih, SHRM-CP',
    'summary': 'Learning & Development | Career Development | Talent Management',
    'location': 'Saudi Arabia'},
   {'link': 'https://sa.linkedin.com/in/afaf-alshammry-00a5aa156',
    'name': 'Afaf Alshammry',
    'summary': 'Human Resources Manager at Saudi German Hospitals',
    'location': "Ha'il, Saudi Arabia"},
   {'link': 'https://www.linkedin.com/in/rodney-parmenter-462173133',
    'name': 'Rodney Parmenter',
    'summary': 'New and used trailer sales at Stuart Tank Sales',
    'location': 'Chili, WI'},
   {'link': 'https://www.linkedin.com/in/edita-cami-69b73336',
    'name': 'Edita Cami',
    'summary': 'Business Recruiter at BlockFi',
    'location': 'Brooklyn, NY'},
   {'link': 'https://www.linkedin.com/in/angela-galli-a13546111',
    'name': 'Angela Galli',
    'summary': 'Customer Success Manager, Groups at Cars.com',
    'location': 'Detroit Metropolitan Area'},
   {'link': 'https://www.linkedin.com/in/colleen-bumb-9a1018aa',
    'name': 'Colleen Bumb',
    'summary': 'Technical Recruiter at Meta',
    'location': 'San Francisco Bay Area'},
   {'link': 'https://www.linkedin.com/in/morganallengolf',
    'name': 'Morgan Allen',
    'summary': 'Corporate Recruiter at AmeriSave Mortgage Corporation',
    'location': 'Greater Phoenix Area'},
   {'link': 'https://www.linkedin.com/in/robyn-mack-508a71a8',
    'name': 'Robyn Mack',
    'summary': 'Promotions Assistant at SpartanNash',
    'location': 'Grand Rapids Metropolitan Area'},
   {'link': 'https://www.linkedin.com/in/jerry-chapman-74054410b',
    'name': 'Jerry Chapman',
    'summary': 'Area Sales Manager at Ashfield Healthcare/ Sprout Pharmaceuticals, Inc.',
    'location': 'Fayetteville, North Carolina Metropolitan Area'},
   {'link': 'https://www.linkedin.com/in/directvirtualneeds',
    'name': 'Kimberly Guerrero',
    'summary': 'Owner of DirectVirtualNeeds â¢ Founder of Desire to Heal and Love â¢ Virtual Assistant Coach of Obtaining Your Vision',
    'location': 'Charlotte, NC'},
   {'link': 'https://www.linkedin.com/in/douglas-martin-1813b9aa',
    'name': 'Douglas Martin',
    'summary': 'President at MAJESTIC HOME INSPECTIONS, INC',
    'location': 'Shorewood, IL'},
   {'link': 'https://www.linkedin.com/in/cynthia-hernandez-12096649',
    'name': 'Cynthia Hernandez',
    'summary': 'Talent Acquisition Business Partner at REVOLVE',
    'location': 'Tustin, CA'},
   {'link': 'https://www.linkedin.com/in/austine-dumas-9b246811b',
    'name': 'Austine Dumas',
    'summary': 'Content Specialist at Spyder box',
    'location': 'United States'},
   {'link': 'https://www.linkedin.com/in/godwin-odus-09b29523',
    'name': 'Godwin Odus',
    'summary': 'Freelance at Super Mega Express',
    'location': 'Bronx, NY'},
   {'link': 'https://www.linkedin.com/in/michael-french-a47103156',
    'name': 'Michael French',
    'summary': "Associate's degree at Valencia College",
    'location': 'Dallas-Fort Worth Metroplex'}],
  'recommendations': [],
  'activities': [{'title': 'Welcome to the team, Corrine! Fun fact: "I\'ve been to China twice."#newhire #womeninbusiness',
    'link': 'https://www.linkedin.com/signup/cold-join',
    'activity_status': 'Liked by Abdulaziz Alyahya'},
   {'title': 'Travel will always be my favorite means of a global & cultural education!! Egypt Jan 2020.',
    'link': 'https://www.linkedin.com/signup/cold-join',
    'activity_status': 'Liked by Abdulaziz Alyahya'}],
  'similarly_named_profiles': [{'name': 'abdulaziz alyahya',
    'link': 'https://sa.linkedin.com/in/abdulaziz-alyahya-a32143a6',
    'summary': 'ÙØ§Ø¦Ø¨ ÙØ¯ÙØ± ØµÙØ§ÙØ© Ø§ÙØ§ÙØ¯ÙØ©  ÙÙ Ø§ÙÙÙØ¦Ø© Ø§ÙØ¹Ø§ÙØ© ÙÙØ±ÙØ§Ø¶Ø©',
    'location': 'Saudi Arabia'},
   {'name': 'Abdulaziz ALYahya',
    'link': 'https://sa.linkedin.com/in/abdulaziz-alyahya-609961158',
    'summary': 'Training Specialist',
    'location': 'Riyadh, Saudi Arabia'},
   {'name': 'Abdulaziz Alyahya',
    'link': 'https://sa.linkedin.com/in/azizmoalyahya',
    'summary': 'Professional Medical Representative at GSK',
    'location': 'Riyadh, Saudi Arabia'},
   {'name': 'Abdulaziz Alyahya',
    'link': 'https://sa.linkedin.com/in/abdulaziz-alyahya-895098a9',
    'summary': 'HR professional at GASCO, National Gas & Industrialization Company',
    'location': 'Saudi Arabia'},
   {'name': 'Abdulaziz Alyahya',
    'link': 'https://sa.linkedin.com/in/abdulaziz-alyahya-7117b052',
    'summary': 'Assistant Deputy Minister for Human Capital at Ministry of Sports',
    'location': 'Saudi Arabia'}],
  'articles': [],
  'groups': [{'profile_pic_url': 'https://media-exp1.licdn.com/dms/image/C4D07AQGnpRs1gtsR2w/group-logo_image-shrink_200x200/0/1631366951511?e=1647684000&v=beta&t=Qg0zyrGmAWesAt3gkcKhMd4Qz9WFRH50UbdJ7SKI_RY',
    'name': 'Rowan University Alumni Association',
    'url': 'https://www.linkedin.com/groups/46689'}],
  'skills': None,
  'inferred_salary': None,
  'github': None,
  'facebook': None,
  'gender': None,
  'birth_date': None,
  'industry': None,
  'interests': None}]

In [20]:
pd.set_option('display.max_columns', None)


us_profile_df = pd.DataFrame(profile_lst)
us_profile_df.head()

,public_identifier,profile_pic_url,background_cover_image_url,first_name,last_name,full_name,occupation,headline,summary,country,country_full_name,city,state,experiences,education,languages,accomplishment_organisations,accomplishment_publications,accomplishment_honors_awards,accomplishment_patents,accomplishment_courses,accomplishment_projects,accomplishment_test_scores,volunteer_work,certifications,connections,people_also_viewed,recommendations,activities,similarly_named_profiles,articles,groups,skills,inferred_salary,github,facebook,gender,birth_date,industry,interests
0,none,https://static-exp1.licdn.com/sc/h/244xhbkr7g4...,https://static-exp1.licdn.com/sc/h/5q92mjc5c51...,Jeff,B.,Jeff B.,"AVP, Life Underwriting at Illinois Mutual",Illinois Mutual,None,US,United States of America,Normal,Illinois,"[{'starts_at': {'day': 1, 'month': 8, 'year': ...","[{'starts_at': None, 'ends_at': None, 'field_o...",[],[],[],[],[],[],[],[],[],"[{'starts_at': None, 'ends_at': None, 'url': N...",380.0,[{'link': 'https://www.linkedin.com/in/katie-m...,[],[],"[{'name': 'Jeff B', 'link': 'https://www.linke...",[],[],None,None,None,None,None,None,None,None
1,a-a-,https://media-exp1.licdn.com/dms/image/C4E03AQ...,https://static-exp1.licdn.com/sc/h/5q92mjc5c51...,Abdulaziz,Alyahya,Abdulaziz Alyahya,None,Student at Rowan University,Iâm an enthusiastic business management and Hu...,US,United States of America,Glassboro,New Jersey,[],"[{'starts_at': {'day': 1, 'month': 1, 'year': ...",[],[],[],[],[],[],[],[],[],[],40.0,[{'link': 'https://sa.linkedin.com/in/mbashara...,[],"[{'title': 'Welcome to the team, Corrine! Fun ...","[{'name': 'abdulaziz alyahya', 'link': 'https:...",[],[{'profile_pic_url': 'https://media-exp1.licdn...,None,None,None,None,None,None,None,None
2,a-a-bailey,https://media-exp1.licdn.com/dms/image/C4E03AQ...,https://static-exp1.licdn.com/sc/h/5q92mjc5c51...,Andrew,Bailey,Andrew Bailey,Science & Technology Counsel at National Pork ...,National Pork Producers Council,Experienced government affairs and public poli...,US,United States of America,Washington,District of Columbia,"[{'starts_at': {'day': 1, 'month': 4, 'year': ...","[{'starts_at': {'day': 1, 'month': 1, 'year': ...",[],[],[],[],[],[],[],[],[],[],400.0,[{'link': 'https://www.linkedin.com/in/jack-fr...,[],[],"[{'name': 'Andrew Bailey', 'link': 'https://ca...",[],[],None,None,None,None,None,None,None,None
3,a-a-cabrera,https://media-exp1.licdn.com/dms/image/C4E03AQ...,https://static-exp1.licdn.com/sc/h/5q92mjc5c51...,Alex,Cabrera,Alex Cabrera,Research Intern at Apple,PhD Student at Carnegie Mellon University,None,US,United States of America,Fairfax County,Virginia,"[{'starts_at': {'day': 1, 'month': 5, 'year': ...","[{'starts_at': {'day': 1, 'month': 1, 'year': ...","[English, Spanish, French]",[],[],"[{'title': 'Stamps Leadership Scholarship', 'i...",[],[],"[{'starts_at': {'day': 1, 'month': 4, 'year': ...",[],[],[],500.0,[{'link': 'https://www.linkedin.com/in/willepp...,[K Kulkarni\n \n \n\n\n\n ...,[{'title': 'Delighted to announce Iâll be inte...,"[{'name': 'Alex Cabrera', 'link': 'https://www...",[],[{'profile_pic_url': 'https://media-exp1.licdn...,None,None,None,None,None,None,None,None
4,a-a-de-oliveira-manuel,https://media-exp1.licdn.com/dms/image/C4E03AQ...,https://media-exp1.licdn.com/dms/image/C4D16AQ...,Alcino de Oliveira,Manuel,Alcino de Oliveira Manuel,Marketing Consultant at Alcino Media LLC,Founder @ AlcinoMedia | Facebook/Meta & Google...,"I use the drive and commitment to help, inspir...",US,United States of America,Miami,Florida,"[{'starts_at': {'day': 1, 'month': 8, 'year': ...",[],[],[],[],[],[],[],[],[],[],[],30.0,[{'link': 'https://www.linkedin.com/in/keith-w...,[],"[{'title': 'Love it ðª', 'link': 'https://www.l...",[],[],[],None,None,None,None,None,None,None,None

In [21]:
us_profile_df.shape

(10000, 40)

In [22]:
us_profile_df[pd.notna(us_profile_df.skills)]

Empty DataFrame
Columns: [public_identifier, profile_pic_url, background_cover_image_url, first_name, last_name, full_name, occupation, headline, summary, country, country_full_name, city, state, experiences, education, languages, accomplishment_organisations, accomplishment_publications, accomplishment_honors_awards, accomplishment_patents, accomplishment_courses, accomplishment_projects, accomplishment_test_scores, volunteer_work, certifications, connections, people_also_viewed, recommendations, activities, similarly_named_profiles, articles, groups, skills, inferred_salary, github, facebook, gender, birth_date, industry, interests]
Index: []

In [23]:
us_profile_df.columns

Index(['public_identifier', 'profile_pic_url', 'background_cover_image_url',
       'first_name', 'last_name', 'full_name', 'occupation', 'headline',
       'summary', 'country', 'country_full_name', 'city', 'state',
       'experiences', 'education', 'languages', 'accomplishment_organisations',
       'accomplishment_publications', 'accomplishment_honors_awards',
       'accomplishment_patents', 'accomplishment_courses',
       'accomplishment_projects', 'accomplishment_test_scores',
       'volunteer_work', 'certifications', 'connections', 'people_also_viewed',
       'recommendations', 'activities', 'similarly_named_profiles', 'articles',
       'groups', 'skills', 'inferred_salary', 'github', 'facebook', 'gender',
       'birth_date', 'industry', 'interests'],
      dtype='object')

In [31]:
us_profile_df['experiences'][9996]

[{'starts_at': {'day': 1, 'month': 11, 'year': 2020},
  'ends_at': None,
  'company': 'Onica, a Rackspace Technology Company',
  'company_linkedin_profile_url': 'https://www.linkedin.com/company/onicagroup',
  'title': 'Engagement Manager',
  'description': 'â¢ Project manager and scrum master for Amazon Web Services (AWS) projects ranging $50k-$3M, managing the scope, budget (burn report), deliverables, and resources to ensure projects are delivered on time and on budget\nâ¢ Projects include cloud migration, modernization, AI and Machine Learning, IoT, and application development \nâ¢ Host weekly status meetings with the client to address current state of each project to ensure clear lines of communication, transparency, and to discuss any current and/or potential risks or opportunities',
  'location': 'Houston, TX, United States',
  'logo_url': 'https://media-exp1.licdn.com/dms/image/C4D0BAQH8pLNk5318YQ/company-logo_100_100/0/1637182419786?e=1655942400&v=beta&t=rqyqWq0cBCWUpeftZyaZaZANLRCvpg6b-PdWhXAv-2g'},
 {'starts_at': {'day': 1, 'month': 1, 'year': 2019},
  'ends_at': {'day': 31, 'month': 7, 'year': 2020},
  'company': 'Cognizant',
  'company_linkedin_profile_url': 'https://www.linkedin.com/company/cognizant',
  'title': 'Senior Management Consultant- Oil and Gas',
  'description': 'Project: AWS Custom Cloud Software Development for Oil and Gas Data Company \nâ¢\tUtilized Microsoft Small Project Framework to create and manage scope, scheduling, and resources for development of custom AWS cloud-based software as part of digital transformation \nâ¢\tManaged simultaneous development of the wireframe, data, and architecture tracks \nâ¢\tHosted weekly status meetings with client and internal stakeholders (Including Product Owner and CIO)\nâ¢\tCreated business requirements specification document that contain high level user stories \nâ¢\tSet up change management grooming sessions with Client SMEs\nâ¢\tUtilized agile project management methodology to track deliverables and worked with Interaction Designer on UI specific wireframes based on the business requirements received from Subject Matter Experts\nâ¢\tCreated and presented deliverables to CIO and stakeholders\nâ¢\tUnder aggressive schedule, delivered MVP on time and under budget',
  'location': 'Houston, Texas Area',
  'logo_url': 'https://media-exp1.licdn.com/dms/image/C4E0BAQEoboJe0-DUPg/company-logo_100_100/0/1625144835174?e=1655942400&v=beta&t=x1B2367XWXYzCTQBUn_0Go0XXlJxlYXiOjUdbNsEzWQ'},
 {'starts_at': {'day': 1, 'month': 6, 'year': 2018},
  'ends_at': {'day': 31, 'month': 8, 'year': 2018},
  'company': 'Hewlett Packard Enterprise',
  'company_linkedin_profile_url': 'https://www.linkedin.com/company/hewlett-packard-enterprise',
  'title': 'OEM Business Planning Strategy Intern',
  'description': 'â¢\tLearned HPE server configuration and what drives customer preferences\nâ¢      Learned contract negotiation strategy between Fortune 50 customers and Business Development by performing pricing strategy\nâ¢\tConstruct complex data and financial models to evaluate business performance\nâ¢       Analyze margin profile based on pricing target',
  'location': 'Houston, Texas Area',
  'logo_url': 'https://media-exp1.licdn.com/dms/image/C4E0BAQH6qdm7VJ5BPA/company-logo_100_100/0/1593697162881?e=1655942400&v=beta&t=nfWKAePFfhlchhCtfjX-IPzN5Jdvn6x5iaJ5CCTI5Ls'},
 {'starts_at': {'day': 1, 'month': 11, 'year': 2017},
  'ends_at': {'day': 30, 'month': 4, 'year': 2018},
  'company': 'StalwartMC',
  'company_linkedin_profile_url': 'https://www.linkedin.com/company/stalwartmc',
  'title': 'Management Consultant',
  'description': 'Project Manager (Jan. 2018-April 2018)\nProject: Technology Implementation for Digital Sports News Source\nâ¢\tUtilized agile project management methodology to effectively lead 8 member delivery team on $1MM new Android and iOS mobile applications and website  \nâ¢\tCreated and managed User Acceptance Testing team of 10, including user scripts and scenarios\nâ¢\tHosted and facilitated twice weekly status meetings with senior management\nâ¢\tCreated and presented project deliverables, including procedural documentation, investor presentations, and BD content to senior management and the CEO\nâ¢\tUtilized MS Project and Project Server for budget, schedule, and risk/issue management\nProject Manager (Nov. 2017- Jan 2018)\nProject: Process Improvement for Mid-Sized General Contractor\nâ¢\tStrategically designed and adapted new candidate sourcing and interviewing process tailored to the client through employee interviews, leveraging industry research and human resource best practices\nâ¢\tMet and exceeded clientâs goals and objectives through meetings with leadership, employee interviews, and independent competitor and best practices research\nâ¢\tReduced clientâs interview process from 30 days to 14, and increased clientâs candidate pool from 1 person per month to 5\nâ¢\tGathered, analyzed, and presented deliverables to the CEO\nâ¢\tDesigned and implemented internal project deliverables as part of consulting team\nâ¢\tUtilized MS Project and Project Server for budget and schedule management',
  'location': 'Houston, Texas Area',
  'logo_url': 'https://media-exp1.licdn.com/dms/image/C4E0BAQHQGI2qW3pS2A/company-logo_100_100/0/1550791035685?e=1655942400&v=beta&t=xMhzuQ9I0QpkZ1OQdCpovign297O0KFu2rHL5-ehDls'},
 {'starts_at': {'day': 1, 'month': 9, 'year': 2014},
  'ends_at': {'day': 30, 'month': 11, 'year': 2017},
  'company': 'Huntsman Corporation',
  'company_linkedin_profile_url': 'https://www.linkedin.com/company/huntsman',
  'title': 'Buyer, Indirect Procurement- Contracts and Services',
  'description': 'â¢\tLed projects as Subject Matter Expert for SAP vendor master data management, SAP Analytics ERP system, and Source to Pay procurement process \nâ¢\tExtended payment terms, negotiated contracts, and leveraged spend through competitive bidding; recorded savings of $215,000 in 2015 and $335,000 in 2016 based on $150MM Annual Spend \nâ¢\tEstablished Master Service Agreements and Work Authorizations to ensure limitation of liability, indemnification, safety standards, and payment terms were established with each vendor prior to performing work at facility \nâ¢\tProtected Huntsmanâs liability on all services performed inside chemical plant, all rental equipment leases, and all HR related transactions for the companyâs largest plant in Geismar, LA \n\nProject: SAP Business Intelligence rollout (Project Manager- Procurement)\nâ¢\tLed cross-departmental colleagues to define KPIs and perform User Acceptance Testing as part of digital transformation \nâ¢\tCustomized training for 15 colleagues in the Procurement Department\nâ¢\tInterviewed members of Procurement team; tailored, designed, and optimized reports for company-wide Purchasing department spanning 5 plants across North America\n\nProject: SAP Ariba Implementation (Project Lead- Procurement)\nâ¢\tLed worldwide procurement team of 20 colleagues to develop worldwide standards for contract execution and vendor management workflows to aid in company-wide digital transformation',
  'location': 'The Woodlands, TX',
  'logo_url': 'https://media-exp1.licdn.com/dms/image/C4E0BAQEWH_v05KQDFA/company-logo_100_100/0/1631628362276?e=1655942400&v=beta&t=7M42Pf9DMl0-Za_utmpvc32XMhgwsafrRhxrRd7dydc'},
 {'starts_at': {'day': 1, 'month': 3, 'year': 2014},
  'ends_at': {'day': 30, 'month': 9, 'year': 2014},
  'company': 'Oxy',
  'company_linkedin_profile_url': 'https://www.linkedin.com/company/oxy',
  'title': 'Contract Analyst',
  'description': 'Project: Oracle I-Procurement Implementation\nâ¢\tIdentified, categorized, and analyzed contracts for conversion from ADP into Oracle invoicing system\nâ¢\tCoordinated with 15 buyers and 200 suppliers of all California operations in order to solve issues related to invoicing and determine ways to improve efficiency\nâ¢\tAssisted contract managers in determining need for extension and/or expansion of budget/scope of contracts\nâ¢\tNotified supplier of change in invoicing by walking the supplier through Oracle once converted contract approved',
  'location': 'Houston, Texas Area',
  'logo_url': 'https://media-exp1.licdn.com/dms/image/C4D0BAQHJTUPHe6nNIw/company-logo_100_100/0/1636654882303?e=1655942400&v=beta&t=v50Zav6q3v_jLlqDzkHct12UGPjsBqYySHubYImwIIo'},
 {'starts_at': {'day': 1, 'month': 2, 'year': 2013},
  'ends_at': {'day': 31, 'month': 3, 'year': 2014},
  'company': 'Arrow Truck Sales',
  'company_linkedin_profile_url': 'https://www.linkedin.com/company/arrow-truck-sales',
  'title': 'Transportation Sales Consultant',
  'description': 'â¢\tProspect, identify, and market available inventory to potential customers\nâ¢\tResponsible for mastering current inventory while identifying equipment used in each industry\nâ¢\tMastered the sales experience while demonstrating excellent communication skills with co-workers and customers\nâ¢\tQuickly adapted to an environment and industry that was previously completely unknown to me',
  'location': 'Houston, Texas Area',
  'logo_url': 'https://media-exp1.licdn.com/dms/image/C560BAQHziOO-3nzeEA/company-logo_100_100/0/1519913293098?e=1655942400&v=beta&t=Uu0pCjthE5kiZI9IEulBPWSP27h_mwz1ZAshPt-lgNQ'},
 {'starts_at': {'day': 1, 'month': 1, 'year': 2008},
  'ends_at': {'day': 31, 'month': 1, 'year': 2013},
  'company': 'Cardiopulmonary Medical Supplies',
  'company_linkedin_profile_url': None,
  'title': 'Customer Service Representative',
  'description': 'â¢\tTaught customers how to effectively use medical equipment  \nâ¢\tCreated a caring environment for patients and customers on a daily basis',
  'location': None,
  'logo_url': None}]

In [24]:
# Saving as csv to make loading easier

us_profile_df.to_csv('../../data/people/us_profiles/10000_random_us_people_profiles.csv')

In [16]:
us_profile_df[pd.notna(us_profile_df['interests'])]

Empty DataFrame
Columns: [public_identifier, profile_pic_url, background_cover_image_url, first_name, last_name, full_name, occupation, headline, summary, country, country_full_name, city, state, experiences, education, languages, accomplishment_organisations, accomplishment_publications, accomplishment_honors_awards, accomplishment_patents, accomplishment_courses, accomplishment_projects, accomplishment_test_scores, volunteer_work, certifications, connections, people_also_viewed, recommendations, activities, similarly_named_profiles, articles, groups, skills, inferred_salary, github, facebook, gender, birth_date, industry, interests]
Index: []

In [32]:
us_profile_df['people_also_viewed'][9996]

[{'link': 'https://www.linkedin.com/in/sharoncowey',
  'name': 'Sharon Cowey',
  'summary': 'Transformation & Change Management Consultant â¥ Program & Project Management | Team Leadership | SAFe 5 Agilist Certified',
  'location': 'Atlanta Metropolitan Area'},
 {'link': 'https://www.linkedin.com/in/andrea-watkins-2996427',
  'name': 'Andrea Watkins',
  'summary': 'Business Transformation & Results Delivery  PMO/RDO/Strategic Planning',
  'location': 'Austin, Texas Metropolitan Area'},
 {'link': 'https://www.linkedin.com/in/susan-clark-84762244',
  'name': 'Susan Clark',
  'summary': 'Senior Consultant | Transformation Management at Cognizant',
  'location': 'Pittsburgh, PA'},
 {'link': 'https://www.linkedin.com/in/janeazzinaro',
  'name': 'Jane Azzinaro, MBA',
  'summary': 'Manager, Strategy Consulting',
  'location': 'Washington DC-Baltimore Area'},
 {'link': 'https://uk.linkedin.com/in/nikola-hristov-frm-cfa',
  'name': 'Nikola Hristov, FRM, CFA',
  'summary': 'Risk Management I Treasury I Investment Management I Data Analytics',
  'location': 'London'},
 {'link': 'https://www.linkedin.com/in/stephenwroblewski',
  'name': 'Stephen Wroblewski',
  'summary': 'Managing Director, Talent & Organization at Accenture Strategy',
  'location': 'Greater Chicago Area'},
 {'link': 'https://www.linkedin.com/in/chris-anderson-749aa26',
  'name': 'Chris Anderson',
  'summary': 'Managing Director at Deloitte Consulting',
  'location': 'Geneva, IL'},
 {'link': 'https://www.linkedin.com/in/markamarino',
  'name': 'Mark Marino',
  'summary': 'Chief Accounting Officer at Rackspace Technology',
  'location': 'San Antonio, TX'},
 {'link': 'https://www.linkedin.com/in/scottshavercpa',
  'name': 'Scott Shaver, CPA, CIA, CISA',
  'summary': 'Chief Audit Executive at Rackspace Technology',
  'location': 'Houston, TX'},
 {'link': 'https://www.linkedin.com/in/stefanie-box-003b447a',
  'name': 'Stefanie Box',
  'summary': 'Chief Legal Officer at Thrive Pet Healthcare',
  'location': 'Boerne, TX'},
 {'link': 'https://www.linkedin.com/in/kentonstuckey',
  'name': 'Kenton Stuckey',
  'summary': 'Professional Services Lead Engagement Manager',
  'location': 'Philadelphia, PA'},
 {'link': 'https://www.linkedin.com/in/thecamilomejia',
  'name': 'Camilo Mejia',
  'summary': 'Automation |  Energy Sustanibility  | Co-Creating the Future | Digital ESG',
  'location': 'United States'},
 {'link': 'https://www.linkedin.com/in/r-jesse-johnson',
  'name': 'Jesse Johnson, MBA',
  'summary': 'Policy Analyst and Federal Regulatory Executive | Government Affairs & Relations | Policy Advisory',
  'location': 'Houston, TX'},
 {'link': 'https://www.linkedin.com/in/holly-windham',
  'name': 'Holly Windham',
  'summary': 'Executive Vice President, Chief Legal and People Officer at Rackspace Technology',
  'location': 'San Antonio, TX'},
 {'link': 'https://www.linkedin.com/in/michelle-peterson-9356b25',
  'name': 'Michelle Peterson',
  'summary': 'VP, Chief of Staff - CEO at Rackspace Technology',
  'location': 'San Antonio, TX'},
 {'link': 'https://www.linkedin.com/in/raquel-loaiza-71748139',
  'name': 'Raquel Loaiza',
  'summary': 'Back Office Manager at Total Gas and Power North America',
  'location': 'Greater Houston'},
 {'link': 'https://www.linkedin.com/in/pizarroeduardo',
  'name': 'Eduardo Pizarro, ACP, SAFe 5 SA, CAPM, CSM',
  'summary': 'Senior Engagement Manager at Rackspace Technology',
  'location': 'United States'},
 {'link': 'https://www.linkedin.com/in/arielhodges',
  'name': 'Ariel Hodges',
  'summary': 'Project Management & Operations Consultant | Project Management | Workflows Expert',
  'location': 'Charlotte Metro'},
 {'link': 'https://www.linkedin.com/in/ameyabhosle',
  'name': 'Ameya Bhosle',
  'summary': 'Helping firms take bold and pragmatic strategic decisions at Strategy& (part of PwC) | Kellogg | Jeep |',
  'location': 'Chicago, IL'},
 {'link': 'https://www.linkedin.com/in/amybenga',
  'name': 'Amy Benga',
  'summary': 'Strategic Engagement Manager',
  'location': 'Greater St. Louis'}]

In [7]:
us_profile_df.dtypes

public_identifier                object
profile_pic_url                  object
background_cover_image_url       object
first_name                       object
last_name                        object
full_name                        object
occupation                       object
headline                         object
summary                          object
country                          object
country_full_name                object
city                             object
state                            object
experiences                      object
education                        object
languages                        object
accomplishment_organisations     object
accomplishment_publications      object
accomplishment_honors_awards     object
accomplishment_patents           object
accomplishment_courses           object
accomplishment_projects          object
accomplishment_test_scores       object
volunteer_work                   object
certifications                   object
connections                     float64
people_also_viewed               object
recommendations                  object
activities                       object
similarly_named_profiles         object
articles                         object
groups                           object
skills                           object
inferred_salary                  object
github                           object
facebook                         object
gender                           object
birth_date                       object
industry                         object
interests                        object
dtype: object

In [11]:
def obj_types(jobs_df):
    c = jobs_df.dtypes
    cols_df = c.reset_index()
    # cols_df.columns
    cols_df = cols_df[cols_df[0]=='object'].reset_index()
    cols_df = cols_df.drop('level_0', axis=1)
    cols_df['max_len'] = 0

    counter = 0
    for i,row in cols_df.iterrows():
        print(i,row[0], row['index'])
        # print( max(jobs_df[row['index']].str.len()))

        # If the entire column is NA
        if sum(pd.isna(jobs_df[row['index']])) == len(jobs_df[row['index']]):
            continue
        
        cols_df.iloc[i,2] = max(jobs_df[row['index']].str.len()) # Max string length of col

    return cols_df

cols_df = obj_types(us_profile_df)
cols_df

0 object public_identifier
1 object profile_pic_url
2 object background_cover_image_url
3 object first_name
4 object last_name
5 object full_name
6 object occupation
7 object headline
8 object summary
9 object country
10 object country_full_name
11 object city
12 object state
13 object experiences
14 object education
15 object languages
16 object accomplishment_organisations
17 object accomplishment_publications
18 object accomplishment_honors_awards
19 object accomplishment_patents
20 object accomplishment_courses
21 object accomplishment_projects
22 object accomplishment_test_scores
23 object volunteer_work
24 object certifications
25 object people_also_viewed
26 object recommendations
27 object activities
28 object similarly_named_profiles
29 object articles
30 object groups
31 object skills
32 object inferred_salary
33 object github
34 object facebook
35 object gender
36 object birth_date
37 object industry
38 object interests

                           index       0  max_len
0              public_identifier  object     60.0
1                profile_pic_url  object    176.0
2     background_cover_image_url  object    186.0
3                     first_name  object     63.0
4                      last_name  object     32.0
5                      full_name  object     71.0
6                     occupation  object    135.0
7                       headline  object    220.0
8                        summary  object      NaN
9                        country  object      2.0
10             country_full_name  object     43.0
11                          city  object     42.0
12                         state  object     43.0
13                   experiences  object     84.0
14                     education  object     30.0
15                     languages  object      9.0
16  accomplishment_organisations  object     17.0
17   accomplishment_publications  object     84.0
18  accomplishment_honors_awards  object     23.0
19        accomplishment_patents  object     25.0
20        accomplishment_courses  object     50.0
21       accomplishment_projects  object     61.0
22    accomplishment_test_scores  object      9.0
23                volunteer_work  object     20.0
24                certifications  object     44.0
25            people_also_viewed  object     20.0
26               recommendations  object     61.0
27                    activities  object      3.0
28      similarly_named_profiles  object      5.0
29                      articles  object      3.0
30                        groups  object     14.0
31                        skills  object      0.0
32               inferred_salary  object      0.0
33                        github  object      0.0
34                      facebook  object      0.0
35                        gender  object      0.0
36                    birth_date  object      0.0
37                      industry  object      0.0
38                     interests  object      0.0